name: Test sqlx (PostgreSQL)

on:
  pull_request:
    types:
      - ready_for_review
  push:
    branches:
      - '*'
env:
  CARGO_TERM_COLOR: always
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Install postgresql server and client
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib postgresql-client build-essential
      - name: Start the database server
        run: |
          sudo systemctl start postgresql.service
      - name: Create the rltbl_db database
        run: |
          sudo su - postgres -c "createuser runner"
          sudo su - postgres -c "createdb -O runner rltbl_db"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install tesh
        run: |
          pip install tesh
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # See https://github.com/actions/setup-node for further options
          node-version: '18.19'
      - name: Run tests
        run: |
          make test_sqlx_postgres
